config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, skip: :registration, path: 'admin', path_names: {sign_in: 'login', sign_out: 'logout'}
  root 'display#index'

  get 'display' => 'display#index'
  get 'display/index'
  get 'display/show'

  get 'admin' => 'admin#index'
  get 'admin/index'
  get 'admin/select'
  get 'admin/shown'
  get 'admin/notice'

  post 'admin/setting'
  post 'admin/maintask'
  post 'admin/togglefeed'
  post 'admin/entrytask'
  post 'admin/checkentry'
  post 'admin/togglenotice'
  post 'admin/reloadnotices'

end

app/views/admin/_entrytable.html.slim
#entryTable

  - if @entries.empty?

    .small-12.columns
      .callout.secondary
        = t('no_entries_found')

  - else
    .small-12.columns
      table.hover

        thead
          tr
            th width=(action_name == 'select' ? "45%" : "55%")
              = t('entry')
            th width="20%"
              = t('image')
            th width="15%"
              = t('expired')
            th width=(action_name == 'select' ? "20%" : "10%")
              = t('show')

        tbody
          - @entries.each do |entry|
            tr

              td colspan=("2" unless entry.image.exists?)
                div
                  strong = link_to raw(entry.title), entry.url, target: "_blank"
                div = raw(entry.summary)

              - if entry.image.exists?
                td
                  = link_to entry.image.url, class: "th"
                    = image_tag entry.image.url(:thumb)
              td
                em = entry.feed.title if entry.feed
                div = l(entry.published)
                - exp = 100*(1-(Time.now-entry.published)/@expiration)
                - case exp
                  - when 20..100
                    - cls = "success"
                  - when 0..19
                    - cls = "alert"
                  - else
                    - exp = 0
                    - cls = "alert"
                .progress.small class=cls role="progressbar"
                  .progress-meter style=("width: " + (10+0.9*exp).to_s + "%")

              td
                .callout.success.showEntry.hide data-alert="" style="margin-bottom: 0;"
                  = t('entry_will_be_shown')
                .callout.alert.deleteEntry.hide data-alert="" style="margin-bottom: 0;"
                  = t('entry_was_deleted')

                = form_tag(admin_checkentry_path, remote: true, class: 'checkEntry', "data-type" => 'json')
                  = hidden_field_tag 'entry_id', entry.id
                  .button-group

                    - if action_name == 'select'
                      button.button.success name='commit' value='show' data-disable-with=t('wait')
                        = icon("check", t('show'))

                    button.button.alert name='commit' value='delete' data-disable-with=t('wait')
                      = icon("remove", t('delete'))

app/views/admin/_feedtable.html.slim
#feedTable

  - if @feeds.empty?

    br
    .small-5.columns
      .callout.secondary
        = t('no_feeds_found')

  - else

    div style="height: 75vh; overflow: scroll;"
      table.hover
        /thead
        /  tr
        /    th width="80%"
        /      = t('feed_title_and_url')
        /    th width="20%"
        /      = t('use')
        tbody
          - @feeds.each do |feed|
            tr
              td
                = link_to feed.title, feed.url, target: "_blank"

              td
                = form_tag(admin_togglefeed_path, remote: true, class: 'toggleFeed')
                  = hidden_field_tag 'feed', feed.id.to_s
                  button.button.expanded.toggleBtn type="submit" name='use' value=(feed.use? ? 'false' : 'true') class=(feed.use? ? 'success' : 'warning') style="padding: 8px; margin-bottom: 0;"
                    span.toggleText class=("hide" unless feed.use?)
                      = icon("power-off", t('enabled'))
                    span.toggleText class=("hide" if feed.use?)
                      = icon("power-off", t('disabled'))

app/views/admin/_noticetable.html.slim
#noticeTable

  - if @notices.empty?

    .small-12.columns
      .callout.secondary
        = t('no_notices_found')

  - else

    .small-12.columns
      table.hover

        thead
          tr
            th width="80%"
              = t('notice')
            th width="20%"
              = t('show')

        tbody
          - @notices.each do |notice|
            tr

              td
                h1 = notice.title
                == notice.summary

              td
                = form_tag(admin_togglenotice_path, remote: true, class: 'toggleNotice')
                  = hidden_field_tag 'notice', notice.id.to_s

                  button.button.toggleBtn type="submit" name='checked' value=(notice.checked? ? 'false' : 'true') class=(notice.checked? ? 'success' : 'warning') style="margin-bottom: 0;"
                    span.toggleText class=("hide" unless notice.checked?)
                      = icon("power-off", t('notice_shown'))
                    span.toggleText class=("hide" if notice.checked?)
                      = icon("power-off", t('notice_unshown'))

app/views/admin/_toolbar.html.slim
= form_tag(admin_entrytask_path, remote: true, id: "entryTask")
  = hidden_field_tag 'action_name', action_name
  .small-12.columns

    .button-group.float-left
      button.button type="submit" name='commit' value='refresh' data-disable-with=t('wait')
        = icon("refresh", t('refresh_list'))

      - unless @mode==false and action_name == 'shown'
        button.button.success type="submit" name='commit' value='fetchall' data-disable-with=t('wait')
          = icon("download", t('fetch_new'))

      button.button.warning type="submit" name='commit' value='cleanup' data-disable-with=t('wait')
        = icon("trash", t('cleanup_old'))

    .button-group.float-right
      - if action_name == 'select'
        button.button.success type="submit" name='commit' value='showall' data-disable-with=t('wait')
          = icon("check", t('show_all'))

      button.button.alert type="submit" name='commit' value='deleteall' data-disable-with=t('wait')
        = icon("remove", t('delete_all'))

app/views/admin/index.html.slim
.row
  .small-5.columns


    = form_tag(admin_setting_path, multipart: true, id: 'setting')

      fieldset

        legend
          strong = t('mode') + " "
          span.has-tip.right data-tooltip="" aria-haspopup="true" title=t('mode_help')
            = icon("info")
        .row
          .small-12.columns
            = radio_button :setting, :mode, true, id: "mode-auto"
            label for="mode-auto"
              span = t('mode_auto') + " "
              span.has-tip.right data-tooltip="" aria-haspopup="true" title=t('mode_auto_help')
                = icon("info")

        .row
          .small-12.columns
            = radio_button :setting, :mode, false, id: "mode-manual"
            label for="mode-manual"
              span = t('mode_manual') + " "
              span.has-tip.right data-tooltip="" aria-haspopup="true" title=t('mode_manual_help')
                = icon("info")

        .row
          .small-9.columns
            label.inline for="expiration-label"
              = t('expiration') + ", " + t("sec")
          .small-3.columns.float-left
            = number_field :setting, :expiration, min: 10, id: "expiration-label"

      fieldset

        legend
          strong = t('style')

        .row
          .small-5.columns
            label for="background-label"
              = t("background")
          .small-4.columns
            = file_field :setting, :background, id: "background-label"
          .small-3.columns
            - if @setting.background.exists?
              button.button.alert name='commit' value='deletebackground' style="padding: 6px;"
                = icon("trash", t('delete_background'))

        - if @setting.background.exists?
          .row
            .small-12.columns
              = link_to @setting.background.url, class: "th"
                = image_tag @setting.background.url(:thumb)

        .row
          .small-9.columns
            label.inline for="displayfrequency-label"
              span = t('display_frequency') + ", " + t("sec") + " "
              span.has-tip.right data-tooltip="" aria-haspopup="true" title=t('display_frequency_help')
                = icon("info")
          .small-3.columns.float-left
            = number_field :setting, :display_frequency, min: 0, step: 0.1, id: "displayfrequency-label"

      fieldset

        legend
          strong = 'Clockwork '
          span.has-tip.right data-tooltip="" aria-haspopup="true" title=t('clockwork_help')
            = icon("info")

        .row
          .small-9.columns
            label for="frequency-label"
              = t('frequency') + ", " + t("sec")
          .small-3.columns.float-left
            = number_field :setting, :frequency, min: 10, id: "frequency-label"

        .row
          .small-12.columns
            = check_box :setting, :autocleanup, id: "autocleanup"
            label for="autocleanup"
              span = t('autocleanup') + " "
              span.has-tip.right data-tooltip="" aria-haspopup="true" title=t('autocleanup_help')
                = icon("info")

      br

      .row
        .small-12.columns
          button.button.success.expanded name='commit' value='save'
            = icon("check", t('save_settings'))


  .small-6.columns
    = form_tag(admin_maintask_path, remote: true, id: "mainTask")
      .row
        .small-4.columns
          button.button.success.expanded type="submit" name='commit' value='fetchall' data-disable-with=t('wait') style="padding: 10px;"
            = icon("download", t('fetch_new'))
        .small-4.columns
          button.button.warning.expanded type="submit" name='commit' value='cleanup' data-disable-with=t('wait') style="padding: 10px;"
            = icon("trash", t('cleanup_old'))
        .small-4.columns
          button.button.alert.expanded type="submit" name='commit' value='revertall' data-disable-with=t('wait') style="padding: 10px;"
            = icon("reply", t('revert_all'))

    == render 'feedtable'

app/views/admin/notice.html.slim
= form_tag(admin_reloadnotices_path, remote: true, id: "noticeReload")
  .small-12.columns
    button.button.success type="submit" name='commit' value='reloadnotices' data-disable-with=t('wait')
      = icon("download", t('reload_notice'))
br

== render 'noticetable'

app/views/admin/select.html.slim
== render 'toolbar'
== render 'entrytable'

app/views/admin/shown.html.slim
== render 'toolbar'
== render 'entrytable'