config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, skip: :registration, path: 'admin', path_names: {sign_in: 'login', sign_out: 'logout'}
  root 'display#index'

  get 'display' => 'display#index'
  get 'display/index'
  get 'display/show'

  get 'admin' => 'admin#index'
  get 'admin/index'
  get 'admin/select'
  get 'admin/shown'
  get 'admin/notice'

  post 'admin/setting'
  post 'admin/maintask'
  post 'admin/togglefeed'
  post 'admin/entrytask'
  post 'admin/checkentry'
  post 'admin/togglenotice'
  post 'admin/reloadnotices'

end

app/views/layouts/admin.html.slim
- content_for :topbar do
  .top-bar
    .top-bar-title
      h4 = link_to t('informator'), admin_index_path

    div
      .top-bar-left
        ul.menu
          li class=("hide" if @mode) id='selectLink'
            = link_to admin_select_path
              span style=("font-weight: bold;" if action_name=='select') = t('entry_selection') + "  "
              span.label.warning#uncheckedLabel = @sizes[:unchecked]
          li
            = link_to admin_shown_path
              span style=("font-weight: bold;" if action_name=='shown') = t('shown_entries') + "  "
              span.label.success#shownLabel = @sizes[:shown]
          li
            = link_to admin_notice_path
              span style=("font-weight: bold;" if action_name=='notice') = t('announcements') + "  "
              span.label.primary#noticeLabel = @sizes[:notice]

      .top-bar-right
        ul.menu
          li
            - case params[:locale]
            - when 'en'
              = link_to 'RUS', locale: :ru
            - when 'ru'
              = link_to 'ENG', locale: :en
            - else
              = link_to 'ENG', locale: :en
          li
            = link_to t('logout'), destroy_admin_session_path, method: :delete

  br
  == yield

== render template: "layouts/application"

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title = t('informator')
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    == content_for?(:topbar) ? yield(:topbar) : yield